main: com.questcave.code
name: QuestCave
version: 1.0
description: QuestCave is a advanced quest plugin with a custom mob system, which allows users to select from easy to hard quests to complete.
api-version: 1.15
authors: [SilverGo,ChickenStyle]
